server:
  port: 8082
  error:
    include-message: always
spring:
  application:
    name: book
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/project_springboot
    username: postgres
    password: Klaus67phobia26!
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: kafkaTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: groupId
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
            value.default.type: com.project.message_service.model.dto.BookRequest
            trusted:
              packages: '*'
          json:
            trusted:
              packages: 'com.project.message_service.model.dto'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/